Feature/arinaho/quiz complete
Spiderman-Trivia-Inc/Spiderman-Trivia-Inc pull request #23
Opened 2024-05-06 19:43 UTC by arinaho-muleba

![Screenshot 2024-05-06 214221](https://github.com/Spiderman-Trivia-Inc/Spiderman-Trivia-Inc/assets/157449847/a9aca94e-afa8-48d5-9b7d-467e3ee55d3f)
![Screenshot 2024-05-06 214335](https://github.com/Spiderman-Trivia-Inc/Spiderman-Trivia-Inc/assets/157449847/e6543188-57da-4bda-b543-3574c34ee846)

2024-05-06 20:20 UTC, tebogo-bbd commented
Looking great. My problem is with the past attempts button the text is not readable. Maybe making the text color the same color as the play again button

2024-05-07 06:52 UTC, tebogo-bbd requested changes

2024-05-07 06:52 UTC, tebogo-bbd commented on frontend/assets/images/meme.png
move this to a memes folder I'm planning on adding a meme for different scores a user can get

2024-05-07 06:53 UTC, arinaho-muleba commented on frontend/assets/images/meme.png
sure

2024-05-09 12:57 UTC, tebogo-bbd approved these changes

2024-05-09 13:00 UTC, sudosf requested changes
Please update the general buttons styles to use their own class names

2024-05-09 13:02 UTC, sudosf commented on frontend/css/style.css
> +    /* margin: 2.5rem; */
bring back the margin

2024-05-09 14:02 UTC, sudosf approved these changes
remove commented padding and change `flex: 1 100%` to just `flex: 1`

2024-05-09 14:16 UTC, merged